version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: expo
    versions:
    - 40.0.1
  - dependency-name: react-navigation
    versions:
    - 4.4.3
  - dependency-name: "@expo/samples"
    versions:
    - 3.0.1
  - dependency-name: jest-expo
    versions:
    - 34.0.1
